// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-cOt-ekGNYWY1rqiy58x86Eal5RBHKq8',
    appId: '1:1009721595166:web:f6dfde192a9220fd10650f',
    messagingSenderId: '1009721595166',
    projectId: 'noodle-quiz',
    authDomain: 'noodle-quiz.firebaseapp.com',
    storageBucket: 'noodle-quiz.appspot.com',
    measurementId: 'G-ZPVFW5FNWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrrNTO0VPEXU0CEp2u5CyZN3TAA7Q2J_Y',
    appId: '1:1009721595166:android:66ea5172c58ffb4910650f',
    messagingSenderId: '1009721595166',
    projectId: 'noodle-quiz',
    storageBucket: 'noodle-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBy5r_VlTEisb7LegXEWQV6ivlQSrGemk',
    appId: '1:1009721595166:ios:22178e43f57b80e610650f',
    messagingSenderId: '1009721595166',
    projectId: 'noodle-quiz',
    storageBucket: 'noodle-quiz.appspot.com',
    iosBundleId: 'com.example.noodleQuiz.RunnerTests',
  );
}
